import { useState } from 'react';
import ImportCyber from './ImportCyber';
import ImportClassic from './ImportClassic';
import ScrollContainer from './components/ScrollContainer/';
import React from 'react';
import Container from './components/Container';
import DropdownMenu from './components/Dropdown';
import './App.css';

function App() {
  return (
    <div className="App">
      <h2> Ozymandias </h2>
      <h3> By Percy Bysshe Shelley </h3>
      <p className="caption"> <a href="https://alzhao.com">Alex Zhao</a> // August 25, 2022 </p>
      <p>
        Ozymandias, in just fourteen lines, touches on the chasm between our expectations for immortal glory
        and the finitude of our accomplishments. Shelley deftly reveals the fragility of human memory; Ozymandias's monument, still rigid
        in the repose of its greatest splendor, are nothing but ruins to us. We can imagine the traveler who tells the tale to be an old Solomon who,
        shaken by his journey, returns home to write, "I have seen all the works that are done under the sun; and, behold, all is vanity and vexation of spirit."
      </p>
      <p>
        All images generated by <a href="https://www.midjourney.com/home/">Midjourney</a> from the text of the poem. Hover over the line to see the exact prompt used to generate the image.
      </p>
      <Container />
      <p className="footer">
      <a href="https://alzhao.com">Back to homepage</a>
      </p>

    </div>
  );
}

export default App;
